14462 ftsprint5
andrey-kolpakov/photo-project-js pull request #3
Opened 2022-04-27 12:56 UTC by andrey-kolpakov

2022-04-30 15:14 UTC, salievvm requested changes

2022-04-30 15:14 UTC, salievvm commented on src/assets/js/forms.js
> +let NewCard = {
Если я правильно понял то этот объект является частью карточек, и если форма к нему обращается - он должен быть вынесен в cards.js

2022-04-30 15:14 UTC, salievvm commented on src/assets/js/popup.js
> +        popupGroup.classList.toggle('popup-group--popup-opened')
Пока не пойму где в попап окна кладется инфа о конкретной картинке. Оставлю комментарий. Возможно найду ниже.

2022-04-30 15:14 UTC, salievvm commented on src/assets/scss/_vars.scss
> +$extra-large: 3000px;   //↓
Тут скорее должно быть 1200 хотя бы, или 1440.

2022-04-30 15:14 UTC, salievvm commented on src/assets/scss/blocks/helper.scss
> +.mb41 {
Нужно двигаться в рамках системы отступов https://uniqtrip.bitrix24.ru/company/personal/user/120/blog/610/

В реальном проекте не должно быть несогласованных отступов, и не кратным какому то общему (2, 4, 8, 16 и т.д.)

2022-04-30 15:14 UTC, salievvm commented on src/assets/scss/blocks/helper.scss
> +            background-color: #3f3f3f;
Цвета лучше вынести в переменные

2022-04-30 15:14 UTC, salievvm commented on src/assets/scss/blocks/helper.scss
> +        background-color: rgba($color: #000000, $alpha: 0);
Цвета лучше вынести в переменные

2022-04-30 15:14 UTC, salievvm commented on src/assets/scss/blocks/popup.scss
> +    max-width: 70% !important;
Лучше не использовать important. Это выручайный инструмент когда уже никак по-другому не сделаешь. Встречается в основном в существующих старых проектах. Тут можно решить ситуацию через обращение по тэгу `div.popup__actual-photo`. Но и так лучше не делать, а просто перезаписать ранее созданный стиль по порядку файлов, или сделать более приоритетным через модификаторы.

2022-04-30 15:14 UTC, salievvm commented on src/assets/scss/blocks/popup.scss
> +#actualImage{
На id лучше не вешать стили, по методологии БЭМ. А создать отдельный класс.

2022-04-30 15:14 UTC, salievvm commented on src/assets/scss/style.scss
> +    background-color: #000;
Опять же лулчше использовать переменные. Будет полезно с темной/светлой темой.

2022-04-30 15:14 UTC, salievvm commented on src/partials/header.html
> +    <hr class="helper__hr helper__hr--fw-mobile-version">
Модификаторы мобильной версии лучше не использовать. Те вещи которые на разных разрешениях должны по разному себя вести лучше делать через breakpoints по уже существующему классу.

2022-05-02 07:42 UTC, andrey-kolpakov commented on src/assets/scss/style.scss
> +    background-color: #000;
Что-то у меня такой строки вообще нет. Но сделаю пару переменных.

2022-05-02 10:18 UTC, andrey-kolpakov commented on src/assets/js/forms.js
> +let NewCard = {
Вынес всё, что было в cards

2022-05-02 10:18 UTC, andrey-kolpakov commented on src/assets/scss/_vars.scss
> +$extra-large: 3000px;   //↓
Тут всё пофиксил

2022-05-02 10:18 UTC, andrey-kolpakov commented on src/assets/scss/blocks/helper.scss
> +.mb41 {
Убрал эти классы, они вообще не юзались. Всё отступы сделал кратными 2

2022-05-02 10:18 UTC, andrey-kolpakov commented on src/assets/scss/blocks/helper.scss
> +            background-color: #3f3f3f;
Вынес

2022-05-02 10:18 UTC, andrey-kolpakov commented on src/assets/scss/blocks/helper.scss
> +        background-color: rgba($color: #000000, $alpha: 0);
Вынес

2022-05-02 10:18 UTC, andrey-kolpakov commented on src/assets/scss/blocks/popup.scss
> +    max-width: 70% !important;
Тут это вообще не нужно было по итогу, убрал. Буду иметь ввиду

2022-05-02 10:18 UTC, andrey-kolpakov commented on src/assets/scss/blocks/popup.scss
> +#actualImage{
пофиксил

2022-05-02 10:18 UTC, andrey-kolpakov commented on src/partials/header.html
> +    <hr class="helper__hr helper__hr--fw-mobile-version">
Убрал

2022-05-03 12:57 UTC, salievvm approved these changes

2022-05-03 12:57 UTC, merged